version = 0.1
[default.deploy.parameters]
stack_name = "powerslog-test"
resolve_s3 = true
s3_prefix = "powerslog-test"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
