name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    uses: unfunco/meta/.github/workflows/release-please.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
