name: PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
    - lambda/**

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@bdb4008b3eb556c67679daa1608cffdd9bc38556
    with:
      working-directory: .
      go-version-file: go.mod
