name: PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
    - lambda/**

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@8a2e3873c609d86b9a67b353a9111bd44171240d # v0.3.0
