name: PR / Lambda

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/pr_lambda.yaml
    - lambda/**/*

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: lambda/go.mod
    - name: Check formatting
      run: test -z "$(go fmt ./...)"
      working-directory: lambda
    - name: Look for suspicious constructs
      run: go vet ./...
      working-directory: lambda
