name: PR / Lambda

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/pr_lambda.yaml
    - lambda/**/*

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@dc15f9a32fe01b1b7cc44e095ab9e9bdd98bb0b7
    with:
      working-directory: lambda
      go-version-file: lambda/go.mod
