name: PR / Lambda

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/pr_lambda.yaml
    - lambda/**/*

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@2cf07936a31dca1b82fe1e447f48e1580c10880e # v0.2.0
    with:
      working-directory: lambda
