name: PR / Lambda

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/pr_lambda.yaml
    - lambda/**/*

jobs:
  verify:
    name: Verify
    uses: unfunco/meta/.github/workflows/verify-go.yaml@bdb4008b3eb556c67679daa1608cffdd9bc38556
    with:
      working-directory: lambda
      go-version-file: go.mod
